version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    container_name: db
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: ${DOCKERHUB_USERNAME}/kittygram_backend
    container_name: backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/app/collected_static
      - media:/app/media

  frontend:
    image: ${DOCKERHUB_USERNAME}/kittygram_frontend
    container_name: frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    image: ${DOCKERHUB_USERNAME}/kittygram_gateway
    container_name: gateway
    depends_on:
      - backend
      - frontend
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media
